In [ ]:
!pip install --upgrade sentence-transformers transformers

Collecting sentence-transformers
  Using cached sentence_transformers-5.1.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.55.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.3.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.34.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.14.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.19.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.7.34)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.7)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.11.0->sentence-transformers) (12.9.86)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.8.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)
Using cached sentence_transformers-5.1.0-py3-none-any.whl (483 kB)
Installing collected packages: sentence-transformers
Successfully installed sentence-transformers-5.1.0

In [ ]:
!pip install --upgrade bitsandbytes

Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.11/dist-packages (0.47.0)
Requirement already satisfied: torch<3,>=2.2 in /usr/local/lib/python3.11/dist-packages (from bitsandbytes) (2.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (4.14.1)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (2025.7.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.2->bitsandbytes) (3.4.0)
Requirement already satisfied: setuptools>=40.8.0 in /usr/local/lib/python3.11/dist-packages (from triton==3.4.0->torch<3,>=2.2->bitsandbytes) (75.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy>=1.13.3->torch<3,>=2.2->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch<3,>=2.2->bitsandbytes) (3.0.2)

In [ ]:
!pip install torch==2.3.0 torchvision==0.18.0

Collecting torch==2.3.0
  Downloading torch-2.3.0-cp312-cp312-manylinux1_x86_64.whl.metadata (26 kB)
Collecting torchvision==0.18.0
  Downloading torchvision-0.18.0-cp312-cp312-manylinux1_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch==2.3.0) (3.19.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.0) (4.14.1)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from torch==2.3.0) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.3.0) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.0) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch==2.3.0) (2025.7.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.3.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.3.0)
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.3.0)
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.3.0)
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.3.0)
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.3.0)
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.3.0)
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.3.0)
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.3.0)
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch==2.3.0)
  Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.3.0)
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision==0.18.0) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision==0.18.0) (11.3.0)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.3.0)
  Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.3.0) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->torch==2.3.0) (1.3.0)
Downloading torch-2.3.0-cp312-cp312-manylinux1_x86_64.whl (779.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 779.1/779.1 MB 1.1 MB/s eta 0:00:00
Downloading torchvision-0.18.0-cp312-cp312-manylinux1_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 94.6 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 1.8 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 2.5 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 71.2 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 42.2 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 1.4 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 9.5 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 23.0 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 9.2 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 5.7 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.2/176.2 MB 3.0 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 7.2 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 37.4 MB/s eta 0:00:00
Installing collected packages: nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch, torchvision
  Attempting uninstall: torch
    Found existing installation: torch 2.8.0+cpu
    Uninstalling torch-2.8.0+cpu:
      Successfully uninstalled torch-2.8.0+cpu
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.23.0+cpu
    Uninstalling torchvision-0.23.0+cpu:
      Successfully uninstalled torchvision-0.23.0+cpu
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.8.0+cpu requires torch==2.8.0, but you have torch 2.3.0 which is incompatible.
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.9.86 nvidia-nvtx-cu12-12.1.105 torch-2.3.0 torchvision-0.18.0

In [ ]:
import os
import json
import requests
import time
import random
import pandas as pd
import numpy as np
import csv
import random
import gc
import pickle
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import jaccard_score
from sklearn.model_selection import ParameterGrid
from sklearn.metrics import ndcg_score, mean_squared_error
# from sentence_transformers import SentenceTransformer
import torch
from transformers import AutoTokenizer, AutoModel, BitsAndBytesConfig

In [ ]:
import os
os.listdir()

['.config',
 'main_metadata.json',
 'similar_questions.csv',
 'drive',
 'sample_data']

# Fetching Data

In [ ]:
url="https://leetcode.com/graphql"

allQ_query="""
query problemsetQuestionList($categorySlug: String, $limit: Int, $skip: Int, $filters: QuestionListFilterInput){
    problemsetQuestionList: questionList(
        categorySlug: $categorySlug
        limit: $limit
        skip: $skip
        filters: $filters
    ){
        total: totalNum
        questions: data{
            questionId
            questionFrontendId
            title
            titleSlug
        }
    }
}
"""

question_query="""
query questionData($titleSlug: String!){
    question(titleSlug: $titleSlug){
        questionId
        questionFrontendId
        title
        content
        likes
        dislikes
        stats
        similarQuestions
        categoryTitle
        hints
        topicTags { name }
        companyTags { name }
        difficulty
        isPaidOnly
        solution { canSeeDetail content }
        hasSolution
        hasVideoSolution
    }
}
"""

In [ ]:
def fetch_all_questions():
    variables={
        "categorySlug":"",
        "limit":10000,
        "skip":0,
        "filters":{}
    }
    payload={
        "query":allQ_query,
        "variables":variables
    }
    response=requests.post(url,json=payload)
    if response.status_code!=200:
        print("Failed to fetch data")
        print(response.json())
        exit()
    data=response.json()
    questions=data['data']['problemsetQuestionList']['questions']
    print(f"Fetched {len(questions)} questions")
    return questions

In [ ]:
def fetch_question(title_slug):
    payload={
        "query":question_query,
        "variables":{
            "titleSlug":title_slug
        }
    }
    retries=8
    base_delay=2
    for tries in range(retries):
        try:
            response=requests.post(url,json=payload,timeout=15)
            delay=random.uniform(1,2)
            time.sleep(delay)
            if response.status_code==200:
                data=response.json()
                q=data['data']['question']
                q['url']=f"https://leetcode.com/problems/{title_slug}/"
                q['titleSlug']=title_slug
                stats = json.loads(q['stats'])
                q["totalAccepted"] = stats.get("totalAccepted")
                q["totalSubmission"] = stats.get("totalSubmission")
                q['totalAcceptedRaw']=stats.get("totalAcceptedRaw")
                q['totalSubmissionRaw']=stats.get('totalSubmissionRaw')
                q["acRate"] = stats.get("acRate")
                return q
            else:
                print(f"retrying {tries+1}/{retries} for {title_slug}")
        except requests.exceptions.RequestException as e:
            print(f"Request error {title_slug}:{e}")
        backoff = base_delay * (2 ** tries) + random.uniform(0, 2)
        print(f"Retrying {tries + 1}/{retries} for {title_slug} after {backoff:.1f}s")
        time.sleep(backoff)
    print(f"Failed to fetch for {title_slug}")
    return None

In [ ]:
session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "Referer": "https://leetcode.com/problemset/all/"
})

questions = fetch_all_questions()
all_questions=[]
save_every=100

# dest=os.path.abspath(os.path.join(os.path.dirname(__file__),"../../data/question_metadata.json"))
dest="question_metadata.json"
already_done=set()
if os.path.exists(dest):
    with open(dest, "r", encoding="utf-8") as f:
        existing = json.load(f)
        all_questions = existing
        already_done = {q["questionFrontendId"] for q in all_questions}
    print(f"Resuming: {len(already_done)} questions already fetched")

for i,q in enumerate(questions):
    title_slug=q['titleSlug']
    if q['questionFrontendId'] in already_done:
        continue
    print(f'{i}/{len(questions)} fetching details for {title_slug}')
    detail=fetch_question(title_slug)
    if detail:
        all_questions.append(detail)
    # Save progress every 100 questions
    if (len(all_questions) % save_every == 0) or (i == len(questions) - 1):
        with open(dest, "w", encoding="utf-8") as f:
            json.dump(all_questions, f, indent=2, ensure_ascii=False)
        print(f"Saved progress ({len(all_questions)} questions)")
    # Every 100 requests, sleep longer (random 30-120 seconds)
    if (len(all_questions) % 100 == 0):
        long_pause = random.uniform(30, 120)
        print(f"Taking a longer break: {long_pause:.1f}s")
        time.sleep(long_pause)
print(f"Saved all questions metadata")

# Creating Similar question Dataset

In [ ]:
dest='main_metadata.json'

In [ ]:
with open(dest,'r',encoding='utf-8') as f:
  metadata=json.load(f)

In [ ]:
similar=[]
for q in metadata:
  similar.append({q['titleSlug']:q['similarQuestions']})
for f in similar:
  for x,y in f.items():
    f[x]=json.loads(y)

In [ ]:
len(metadata)

3624

In [ ]:
for sim in similar:
  for x,y in sim.items():
    temp=[]
    for tags in y:
      temp.append(tags['titleSlug'])
    sim[x]=temp

In [ ]:
similar

### Positive pairs

In [ ]:
raw_data=[]
prev=set()
for sim in similar:
  for x,y in sim.items():
    for q2 in y:
      canonical_pair = tuple(sorted((x, q2)))
      if canonical_pair not in prev:
        prev.add(canonical_pair)
        raw_data.append({'question1':x,'question2':q2,'score':1.0})
len(raw_data)

### Negative pairs and Saving dataset

Guessed weights - Only for filtering - prevent pair of questions that maybe similar from being marked as a dissimilar pair

In [ ]:
weights=[0.3,0.5,0.2]

Note: Dont forget to run the baseline() function in the Grid Search section before running this

* metadata & similar from leetcode
* embeddings from repo

In [ ]:
n=len(raw_data)
for _ in range(n):
  while True:
    x=random.randint(0,3182)
    y=random.randint(0,3182)
    while x==y:
      y=random.randint(0,len(similar)-1)
    str_x=list(similar[x].keys())[0]
    str_y=list(similar[y].keys())[0]
    if str_x not in name_embeds.keys() or str_y not in name_embeds.keys():
        continue
    canonical_pair=tuple(sorted((str_x,str_y)))
    if canonical_pair not in prev and baseline(weights,str_x,str_y)<0.4:
      prev.add(canonical_pair)
      raw_data.append({'question1':str_x,'question2':str_y,'score':0.0})
      break
print(len(raw_data)-n)

In [ ]:
raw_data

In [ ]:
len(raw_data)

In [ ]:
with open('similar_questions.csv','w',newline='') as f:
  fields=['question1','question2','score']
  writer=csv.DictWriter(f,fieldnames=fields)
  writer.writeheader()
  writer.writerows(raw_data)
print("saved")

Checking for duplicates

In [ ]:
df = pd.read_csv('/similar_questions.csv')
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

In [ ]:
with open('main_metadata.json','r',encoding='utf-8') as f:
  main_metadata=json.load(f)
data={}
for meta in main_metadata:
  data[meta['titleSlug']]={
          'title':meta['title'],
          'code':meta['code'],
          'tags':meta['tags']
      }

with open('question_data.json','w',encoding='utf-8') as f:
  json.dump(data,f,indent=2,ensure_ascii=False)

In [ ]:
data['as-far-from-land-as-possible']

In [ ]:
with open('/question_data.json','r',encoding='utf-8') as f:
    n=json.load(f)
print(len(n))

# Embeddings

In [ ]:
name_embeds={}
code_embeds={}

In [ ]:
name_model=SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")

In [ ]:
model_name = "nomic-ai/nomic-embed-code"
bnb_config = BitsAndBytesConfig(
    load_in_8bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False
)

# ✅ Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

# ✅ Load model in 8-bit with automatic device map
model = AutoModel.from_pretrained(
    model_name,
    quantization_config=bnb_config,               # compress to 8-bit\
    device_map="auto",               # split layers across available GPUs
    offload_folder="offload",
)

print("Model loaded successfully!")

In [ ]:
def get_embeddings(snippets, batch_size=2, max_length=512):
    embeddings = []
    for i in range(0, len(snippets), batch_size):
        batch = snippets[i:i+batch_size]
        inputs = tokenizer(
            batch,
            padding=True,
            truncation=True,
            max_length=max_length,
            return_tensors="pt"
        ).to(model.device)

        with torch.no_grad():
            outputs = model(**inputs)

        # mean pooling
        batch_embeds = outputs.last_hidden_state.mean(dim=1)
        embeddings.extend(batch_embeds.cpu().numpy())

        # free memory
        del inputs, outputs, batch_embeds
        gc.collect()
        torch.cuda.empty_cache()
    return embeddings

In [ ]:
with open('/kaggle/working/question_data.json','r',encoding='utf-8') as f:
    question_data = json.load(f)

code_embeds = {}
batch_sz = 1  # keep small for memory safety

for i in range(0, len(question_data), batch_sz):
    batch = question_data[i:i+batch_sz]
    batch_codes = []
    batch_slugs = []

    for q in batch:
        slug, details = list(q.items())[0]
        batch_codes.append(details['code'])
        batch_slugs.append(slug)

    # Encode code snippets
    batch_code_embeddings = get_embeddings(batch_codes, batch_size=1)

    for j, slug in enumerate(batch_slugs):
        code_embeds[slug] = batch_code_embeddings[j]

    # Save partial results
    with open('code_embeds.pkl', 'wb') as f:
        pickle.dump(code_embeds, f)

    print(f"Processed {i+batch_sz} / {len(question_data)}")

# Save
with open('code_embeds.pkl', 'wb') as f:
    pickle.dump(code_embeds, f)

In [ ]:
batch_sz=10 # prevent overloading the RAM
with open('/kaggle/working/question_data.json','r',encoding='utf-8') as f:
  question_data=json.load(f)

# device= 'cuda:1' if torch.cuda.is_available() else 'cpu'
# name_model.to(device)
print('loading')
for i in range(0,len(question_data),batch_sz):
    batch=question_data[i:i+batch_sz]
    batch_names=[]
    batch_slugs=[]
    for q in batch:
        slug,details=list(q.items())[0]
        batch_names.append(details['title'])
        batch_slugs.append(slug)

    batch_name_embeddings=name_model.encode(batch_names)

    for j,slug in enumerate(batch_slugs):
        name_embeds[slug]=batch_name_embeddings[j]
    with open('name_embeds.pkl', 'wb') as f:
        pickle.dump(name_embeds, f)
    print(f"Processed {i+batch_sz} questions")

In [ ]:
len(name_embeds)

In [ ]:
with open('/kaggle/working/name_embeds.pkl','rb') as f:
    data=pickle.load(f)
len(data)

# Grid Search

In [ ]:
with open('code_embeds.pkl','rb') as f:
    code_embeds=pickle.load(f)
with open('name_embeds.pkl','rb') as f:
    name_embeds=pickle.load(f)

In [ ]:
len(tags)

3624

In [ ]:
tags={}
for q in metadata:
  tags[q['titleSlug']]=q['tags']
tags

{'two-sum': ['Array', 'Hash Table'],
 'add-two-numbers': ['Linked List', 'Math', 'Recursion'],
 'longest-substring-without-repeating-characters': ['Hash Table',
  'String',
  'Sliding Window'],
 'median-of-two-sorted-arrays': ['Array',
  'Binary Search',
  'Divide and Conquer'],
 'longest-palindromic-substring': ['Two Pointers',
  'String',
  'Dynamic Programming'],
 'zigzag-conversion': ['String'],
 'reverse-integer': ['Math'],
 'string-to-integer-atoi': ['String'],
 'palindrome-number': ['Math'],
 'regular-expression-matching': ['String', 'Dynamic Programming', 'Recursion'],
 'container-with-most-water': ['Array', 'Two Pointers', 'Greedy'],
 'integer-to-roman': ['Hash Table', 'Math', 'String'],
 'roman-to-integer': ['Hash Table', 'Math', 'String'],
 'longest-common-prefix': ['Array', 'String', 'Trie'],
 '3sum': ['Array', 'Two Pointers', 'Sorting'],
 '3sum-closest': ['Array', 'Two Pointers', 'Sorting'],
 'letter-combinations-of-a-phone-number': ['Hash Table',
  'String',
  'Backtracking'],
 '4sum': ['Array', 'Two Pointers', 'Sorting'],
 'remove-nth-node-from-end-of-list': ['Linked List', 'Two Pointers'],
 'valid-parentheses': ['String', 'Stack'],
 'merge-two-sorted-lists': ['Linked List', 'Recursion'],
 'generate-parentheses': ['String', 'Dynamic Programming', 'Backtracking'],
 'merge-k-sorted-lists': ['Linked List',
  'Divide and Conquer',
  'Heap (Priority Queue)',
  'Merge Sort'],
 'swap-nodes-in-pairs': ['Linked List', 'Recursion'],
 'reverse-nodes-in-k-group': ['Linked List', 'Recursion'],
 'remove-duplicates-from-sorted-array': ['Array', 'Two Pointers'],
 'remove-element': ['Array', 'Two Pointers'],
 'find-the-index-of-the-first-occurrence-in-a-string': ['Two Pointers',
  'String',
  'String Matching'],
 'divide-two-integers': ['Math', 'Bit Manipulation'],
 'substring-with-concatenation-of-all-words': ['Hash Table',
  'String',
  'Sliding Window'],
 'next-permutation': ['Array', 'Two Pointers'],
 'longest-valid-parentheses': ['String', 'Dynamic Programming', 'Stack'],
 'search-in-rotated-sorted-array': ['Array', 'Binary Search'],
 'find-first-and-last-position-of-element-in-sorted-array': ['Array',
  'Binary Search'],
 'search-insert-position': ['Array', 'Binary Search'],
 'valid-sudoku': ['Array', 'Hash Table', 'Matrix'],
 'sudoku-solver': ['Array', 'Hash Table', 'Backtracking', 'Matrix'],
 'count-and-say': ['String'],
 'combination-sum': ['Array', 'Backtracking'],
 'combination-sum-ii': ['Array', 'Backtracking'],
 'first-missing-positive': ['Array', 'Hash Table'],
 'trapping-rain-water': ['Array',
  'Two Pointers',
  'Dynamic Programming',
  'Stack',
  'Monotonic Stack'],
 'multiply-strings': ['Math', 'String', 'Simulation'],
 'wildcard-matching': ['String', 'Dynamic Programming', 'Greedy', 'Recursion'],
 'jump-game-ii': ['Array', 'Dynamic Programming', 'Greedy'],
 'permutations': ['Array', 'Backtracking'],
 'permutations-ii': ['Array', 'Backtracking', 'Sorting'],
 'rotate-image': ['Array', 'Math', 'Matrix'],
 'group-anagrams': ['Array', 'Hash Table', 'String', 'Sorting'],
 'powx-n': ['Math', 'Recursion'],
 'n-queens': ['Array', 'Backtracking'],
 'n-queens-ii': ['Backtracking'],
 'maximum-subarray': ['Array', 'Divide and Conquer', 'Dynamic Programming'],
 'spiral-matrix': ['Array', 'Matrix', 'Simulation'],
 'jump-game': ['Array', 'Dynamic Programming', 'Greedy'],
 'merge-intervals': ['Array', 'Sorting'],
 'insert-interval': ['Array'],
 'length-of-last-word': ['String'],
 'spiral-matrix-ii': ['Array', 'Matrix', 'Simulation'],
 'permutation-sequence': ['Math', 'Recursion'],
 'rotate-list': ['Linked List', 'Two Pointers'],
 'unique-paths': ['Math', 'Dynamic Programming', 'Combinatorics'],
 'unique-paths-ii': ['Array', 'Dynamic Programming', 'Matrix'],
 'minimum-path-sum': ['Array', 'Dynamic Programming', 'Matrix'],
 'valid-number': ['String'],
 'plus-one': ['Array', 'Math'],
 'add-binary': ['Math', 'String', 'Bit Manipulation', 'Simulation'],
 'text-justification': ['Array', 'String', 'Simulation'],
 'sqrtx': ['Math', 'Binary Search'],
 'climbing-stairs': ['Math', 'Dynamic Programming', 'Memoization'],
 'simplify-path': ['String', 'Stack'],
 'edit-distance': ['String', 'Dynamic Programming'],
 'set-matrix-zeroes': ['Array', 'Hash Table', 'Matrix'],
 'search-a-2d-matrix': ['Array', 'Binary Search', 'Matrix'],
 'sort-colors': ['Array', 'Two Pointers', 'Sorting'],
 'minimum-window-substring': ['Hash Table', 'String', 'Sliding Window'],
 'combinations': ['Backtracking'],
 'subsets': ['Array', 'Backtracking', 'Bit Manipulation'],
 'word-search': ['Array',
  'String',
  'Backtracking',
  'Depth-First Search',
  'Matrix'],
 'remove-duplicates-from-sorted-array-ii': ['Array', 'Two Pointers'],
 'search-in-rotated-sorted-array-ii': ['Array', 'Binary Search'],
 'remove-duplicates-from-sorted-list-ii': ['Linked List', 'Two Pointers'],
 'remove-duplicates-from-sorted-list': ['Linked List'],
 'largest-rectangle-in-histogram': ['Array', 'Stack', 'Monotonic Stack'],
 'maximal-rectangle': ['Array',
  'Dynamic Programming',
  'Stack',
  'Matrix',
  'Monotonic Stack'],
 'partition-list': ['Linked List', 'Two Pointers'],
 'scramble-string': ['String', 'Dynamic Programming'],
 'merge-sorted-array': ['Array', 'Two Pointers', 'Sorting'],
 'gray-code': ['Math', 'Backtracking', 'Bit Manipulation'],
 'subsets-ii': ['Array', 'Backtracking', 'Bit Manipulation'],
 'decode-ways': ['String', 'Dynamic Programming'],
 'reverse-linked-list-ii': ['Linked List'],
 'restore-ip-addresses': ['String', 'Backtracking'],
 'binary-tree-inorder-traversal': ['Stack',
  'Tree',
  'Depth-First Search',
  'Binary Tree'],
 'unique-binary-search-trees-ii': ['Dynamic Programming',
  'Backtracking',
  'Tree',
  'Binary Search Tree',
  'Binary Tree'],
 'unique-binary-search-trees': ['Math',
  'Dynamic Programming',
  'Tree',
  'Binary Search Tree',
  'Binary Tree'],
 'interleaving-string': ['String', 'Dynamic Programming'],
 'validate-binary-search-tree': ['Tree',
  'Depth-First Search',
  'Binary Search Tree',
  'Binary Tree'],
 'recover-binary-search-tree': ['Tree',
  'Depth-First Search',
  'Binary Search Tree',
  'Binary Tree'],
 'same-tree': ['Tree',
  'Depth-First Search',
  'Breadth-First Search',
  'Binary Tree'],
 'symmetric-tree': ['Tree',
  'Depth-First Search',
  'Breadth-First Search',
  'Binary Tree'],
 'binary-tree-level-order-traversal': ['Tree',
  'Breadth-First Search',
  'Binary Tree'],
 'binary-tree-zigzag-level-order-traversal': ['Tree',
  'Breadth-First Search',
  'Binary Tree'],
 'maximum-depth-of-binary-tree': ['Tree',
  'Depth-First Search',
  'Breadth-First Search',
  'Binary Tree'],
 'construct-binary-tree-from-preorder-and-inorder-traversal': ['Array',
  'Hash Table',
  'Divide and Conquer',
  'Tree',
  'Binary Tree'],
 'construct-binary-tree-from-inorder-and-postorder-traversal': ['Array',
  'Hash Table',
  'Divide and Conquer',
  'Tree',
  'Binary Tree'],
 'binary-tree-level-order-traversal-ii': ['Tree',
  'Breadth-First Search',
  'Binary Tree'],
 'convert-sorted-array-to-binary-search-tree': ['Array',
  'Divide and Conquer',
  'Tree',
  'Binary Search Tree',
  'Binary Tree'],
 'convert-sorted-list-to-binary-search-tree': ['Linked List',
  'Divide and Conquer',
  'Tree',
  'Binary Search Tree',
  'Binary Tree'],
 'balanced-binary-tree': ['Tree', 'Depth-First Search', 'Binary Tree'],
 'minimum-depth-of-binary-tree': ['Tree',
  'Depth-First Search',
  'Breadth-First Search',
  'Binary Tree'],
 'path-sum': ['Tree',
  'Depth-First Search',
  'Breadth-First Search',
  'Binary Tree'],
 'path-sum-ii': ['Backtracking', 'Tree', 'Depth-First Search', 'Binary Tree'],
 'flatten-binary-tree-to-linked-list': ['Linked List',
  'Stack',
  'Tree',
  'Depth-First Search',
  'Binary Tree'],
 'distinct-subsequences': ['String', 'Dynamic Programming'],
 'populating-next-right-pointers-in-each-node': ['Linked List',
  'Tree',
  'Depth-First Search',
  'Breadth-First Search',
  'Binary Tree'],
 'populating-next-right-pointers-in-each-node-ii': ['Linked List',
  'Tree',
  'Depth-First Search',
  'Breadth-First Search',
  'Binary Tree'],
 'pascals-triangle': ['Array', 'Dynamic Programming'],
 'pascals-triangle-ii': ['Array', 'Dynamic Programming'],
 'triangle': ['Array', 'Dynamic Programming'],
 'best-time-to-buy-and-sell-stock': ['Array', 'Dynamic Programming'],
 'best-time-to-buy-and-sell-stock-ii': ['Array',
  'Dynamic Programming',
  'Greedy'],
 'best-time-to-buy-and-sell-stock-iii': ['Array', 'Dynamic Programming'],
 'binary-tree-maximum-path-sum': ['Dynamic Programming',
  'Tree',
  'Depth-First Search',
  'Binary Tree'],
 'valid-palindrome': ['Two Pointers', 'String'],
 'word-ladder-ii': ['Hash Table',
  'String',
  'Backtracking',
  'Breadth-First Search'],
 'word-ladder': ['Hash Table', 'String', 'Breadth-First Search'],
 'longest-consecutive-sequence': ['Array', 'Hash Table', 'Union Find'],
 'sum-root-to-leaf-numbers': ['Tree', 'Depth-First Search', 'Binary Tree'],
 'surrounded-regions': ['Array',
  'Depth-First Search',
  'Breadth-First Search',
  'Union Find',
  'Matrix'],
 'palindrome-partitioning': ['String', 'Dynamic Programming', 'Backtracking'],
 'palindrome-partitioning-ii': ['String', 'Dynamic Programming'],
 'clone-graph': ['Hash Table',
  'Depth-First Search',
  'Breadth-First Search',
  'Graph'],
 'gas-station': ['Array', 'Greedy'],
 'candy': ['Array', 'Greedy'],
 'single-number': ['Array', 'Bit Manipulation'],
 'single-number-ii': ['Array', 'Bit Manipulation'],
 'copy-list-with-random-pointer': ['Hash Table', 'Linked List'],
 'word-break': ['Array',
  'Hash Table',
  'String',
  'Dynamic Programming',
  'Trie',
  'Memoization'],
 'word-break-ii': ['Array',
  'Hash Table',
  'String',
  'Dynamic Programming',
  'Backtracking',
  'Trie',
  'Memoization'],
 'linked-list-cycle': ['Hash Table', 'Linked List', 'Two Pointers'],
 'linked-list-cycle-ii': ['Hash Table', 'Linked List', 'Two Pointers'],
 'reorder-list': ['Linked List', 'Two Pointers', 'Stack', 'Recursion'],
 'binary-tree-preorder-traversal': ['Stack',
  'Tree',
  'Depth-First Search',
  'Binary Tree'],
 'binary-tree-postorder-traversal': ['Stack',
  'Tree',
  'Depth-First Search',
  'Binary Tree'],
 'lru-cache': ['Hash Table', 'Linked List', 'Design', 'Doubly-Linked List'],
 'insertion-sort-list': ['Linked List', 'Sorting'],
 'sort-list': ['Linked List',
  'Two Pointers',
  'Divide and Conquer',
  'Sorting',
  'Merge Sort'],
 'max-points-on-a-line': ['Array', 'Hash Table', 'Math', 'Geometry'],
 'evaluate-reverse-polish-notation': ['Array', 'Math', 'Stack'],
 'reverse-words-in-a-string': ['Two Pointers', 'String'],
 'maximum-product-subarray': ['Array', 'Dynamic Programming'],
 'find-minimum-in-rotated-sorted-array': ['Array', 'Binary Search'],
 'find-minimum-in-rotated-sorted-array-ii': ['Array', 'Binary Search'],
 'min-stack': ['Stack', 'Design'],
 'binary-tree-upside-down': ['Tree', 'Depth-First Search', 'Binary Tree'],
 'read-n-characters-given-read4': ['Array', 'Simulation', 'Interactive'],
 'read-n-characters-given-read4-ii-call-multiple-times': ['Array',
  'Simulation',
  'Interactive'],
 'longest-substring-with-at-most-two-distinct-characters': ['Hash Table',
  'String',
  'Sliding Window'],
 'intersection-of-two-linked-lists': ['Hash Table',
  'Linked List',
  'Two Pointers'],
 'one-edit-distance': ['Two Pointers', 'String'],
 'find-peak-element': ['Array', 'Binary Search'],
 'missing-ranges': ['Array'],
 'maximum-gap': ['Array', 'Sorting', 'Bucket Sort', 'Radix Sort'],
 'compare-version-numbers': ['Two Pointers', 'String'],
 'fraction-to-recurring-decimal': ['Hash Table', 'Math', 'String'],
 'two-sum-ii-input-array-is-sorted': ['Array',
  'Two Pointers',
  'Binary Search'],
 'excel-sheet-column-title': ['Math', 'String'],
 'majority-element': ['Array',
  'Hash Table',
  'Divide and Conquer',
  'Sorting',
  'Counting'],
 'two-sum-iii-data-structure-design': ['Array',
  'Hash Table',
  'Two Pointers',
  'Design',
  'Data Stream'],
 'excel-sheet-column-number': ['Math', 'String'],
 'factorial-trailing-zeroes': ['Math'],
 'binary-search-tree-iterator': ['Stack',
  'Tree',
  'Design',
  'Binary Search Tree',
  'Binary Tree',
  'Iterator'],
 'dungeon-game': ['Array', 'Dynamic Programming', 'Matrix'],
 'combine-two-tables': ['Database'],
 'second-highest-salary': ['Database'],
 'nth-highest-salary': ['Database'],
 'rank-scores': ['Database'],
 'largest-number': ['Array', 'String', 'Greedy', 'Sorting'],
 'consecutive-numbers': ['Database'],
 'employees-earning-more-than-their-managers': ['Database'],
 'duplicate-emails': ['Database'],
 'customers-who-never-order': ['Database'],
 'department-highest-salary': ['Database'],
 'department-top-three-salaries': ['Database'],
 'reverse-words-in-a-string-ii': ['Two Pointers', 'String'],
 'best-time-to-buy-and-sell-stock-iv': ['Array', 'Dynamic Programming'],
 'rotate-array': ['Array', 'Math', 'Two Pointers'],
 'reverse-bits': ['Divide and Conquer', 'Bit Manipulation'],
 'number-of-1-bits': ['Divide and Conquer', 'Bit Manipulation'],
 'word-frequency': ['Shell'],
 'valid-phone-numbers': ['Shell'],
 'transpose-file': ['Shell'],
 'tenth-line': ['Shell'],
 'delete-duplicate-emails': ['Database'],
 'rising-temperature': ['Database'],
 'house-robber': ['Array', 'Dynamic Programming'],
 'binary-tree-right-side-view': ['Tree',
  'Depth-First Search',
  'Breadth-First Search',
  'Binary Tree'],
 'number-of-islands': ['Array',
  'Depth-First Search',
  'Breadth-First Search',
  'Union Find',
  'Matrix'],
 'bitwise-and-of-numbers-range': ['Bit Manipulation'],
 'happy-number': ['Hash Table', 'Math', 'Two Pointers'],
 'remove-linked-list-elements': ['Linked List', 'Recursion'],
 'count-primes': ['Array', 'Math', 'Enumeration', 'Number Theory'],
 'isomorphic-strings': ['Hash Table', 'String'],
 'reverse-linked-list': ['Linked List', 'Recursion'],
 'course-schedule': ['Depth-First Search',
  'Breadth-First Search',
  'Graph',
  'Topological Sort'],
 'implement-trie-prefix-tree': ['Hash Table', 'String', 'Design', 'Trie'],
 'minimum-size-subarray-sum': ['Array',
  'Binary Search',
  'Sliding Window',
  'Prefix Sum'],
 'course-schedule-ii': ['Depth-First Search',
  'Breadth-First Search',
  'Graph',
  'Topological Sort'],
 'design-add-and-search-words-data-structure': ['String',
  'Depth-First Search',
  'Design',
  'Trie'],
 'word-search-ii': ['Array', 'String', 'Backtracking', 'Trie', 'Matrix'],
 'house-robber-ii': ['Array', 'Dynamic Programming'],
 'shortest-palindrome': ['String',
  'Rolling Hash',
  'String Matching',
  'Hash Function'],
 'kth-largest-element-in-an-array': ['Array',
  'Divide and Conquer',
  'Sorting',
  'Heap (Priority Queue)',
  'Quickselect'],
 'combination-sum-iii': ['Array', 'Backtracking'],
 'contains-duplicate': ['Array', 'Hash Table', 'Sorting'],
 'the-skyline-problem': ['Array',
  'Divide and Conquer',
  'Binary Indexed Tree',
  'Segment Tree',
  'Line Sweep',
  'Heap (Priority Queue)',
  'Ordered Set'],
 'contains-duplicate-ii': ['Array', 'Hash Table', 'Sliding Window'],
 'contains-duplicate-iii': ['Array',
  'Sliding Window',
  'Sorting',
  'Bucket Sort',
  'Ordered Set'],
 'maximal-square': ['Array', 'Dynamic Programming', 'Matrix'],
 'count-complete-tree-nodes': ['Binary Search',
  'Bit Manipulation',
  'Tree',
  'Binary Tree'],
 'rectangle-area': ['Math', 'Geometry'],
 'basic-calculator': ['Math', 'String', 'Stack', 'Recursion'],
 'implement-stack-using-queues': ['Stack', 'Design', 'Queue'],
 'invert-binary-tree': ['Tree',
  'Depth-First Search',
  'Breadth-First Search',
  'Binary Tree'],
 'basic-calculator-ii': ['Math', 'String', 'Stack'],
 'summary-ranges': ['Array'],
 'majority-element-ii': ['Array', 'Hash Table', 'Sorting', 'Counting'],
 'kth-smallest-element-in-a-bst': ['Tree',
  'Depth-First Search',
  'Binary Search Tree',
  'Binary Tree'],
 'power-of-two': ['Math', 'Bit Manipulation', 'Recursion'],
 'implement-queue-using-stacks': ['Stack', 'Design', 'Queue'],
 'number-of-digit-one': ['Math', 'Dynamic Programming', 'Recursion'],
 'palindrome-linked-list': ['Linked List',
  'Two Pointers',
  'Stack',
  'Recursion'],
 'lowest-common-ancestor-of-a-binary-search-tree': ['Tree',
  'Depth-First Search',
  'Binary Search Tree',
  'Binary Tree'],
 'lowest-common-ancestor-of-a-binary-tree': ['Tree',
  'Depth-First Search',
  'Binary Tree'],
 'delete-node-in-a-linked-list': ['Linked List'],
 'product-of-array-except-self': ['Array', 'Prefix Sum'],
 'sliding-window-maximum': ['Array',
  'Queue',
  'Sliding Window',
  'Heap (Priority Queue)',
  'Monotonic Queue'],
 'search-a-2d-matrix-ii': ['Array',
  'Binary Search',
  'Divide and Conquer',
  'Matrix'],
 'different-ways-to-add-parentheses': ['Math',
  'String',
  'Dynamic Programming',
  'Recursion',
  'Memoization'],
 'valid-anagram': ['Hash Table', 'String', 'Sorting'],
 'shortest-word-distance': ['Array', 'String'],
 'shortest-word-distance-ii': ['Array',
  'Hash Table',
  'Two Pointers',
  'String',
  'Design'],
 'shortest-word-distance-iii': ['Array', 'String'],
 'strobogrammatic-number': ['Hash Table', 'Two Pointers', 'String'],
 'strobogrammatic-number-ii': ['Array', 'String', 'Recursion'],
 'strobogrammatic-number-iii': ['Array', 'String', 'Recursion'],
 'group-shifted-strings': ['Array', 'Hash Table', 'String'],
 'count-univalue-subtrees': ['Tree', 'Depth-First Search', 'Binary Tree'],
 'flatten-2d-vector': ['Array', 'Two Pointers', 'Design', 'Iterator'],
 'meeting-rooms': ['Array', 'Sorting'],
 'meeting-rooms-ii': ['Array',
  'Two Pointers',
  'Greedy',
  'Sorting',
  'Heap (Priority Queue)',
  'Prefix Sum'],
 'factor-combinations': ['Backtracking'],
 'verify-preorder-sequence-in-binary-search-tree': ['Array',
  'Stack',
  'Tree',
  'Binary Search Tree',
  'Recursion',
  'Monotonic Stack',
  'Binary Tree'],
 'paint-house': ['Array', 'Dynamic Programming'],
 'binary-tree-paths': ['String',
  'Backtracking',
  'Tree',
  'Depth-First Search',
  'Binary Tree'],
 'add-digits': ['Math', 'Simulation', 'Number Theory'],
 '3sum-smaller': ['Array', 'Two Pointers', 'Binary Search', 'Sorting'],
 'single-number-iii': ['Array', 'Bit Manipulation'],
 'graph-valid-tree': ['Depth-First Search',
  'Breadth-First Search',
  'Union Find',
  'Graph'],
 'trips-and-users': ['Database'],
 'ugly-number': ['Math'],
 'ugly-number-ii': ['Hash Table',
  'Math',
  'Dynamic Programming',
  'Heap (Priority Queue)'],
 'paint-house-ii': ['Array', 'Dynamic Programming'],
 'palindrome-permutation': ['Hash Table', 'String', 'Bit Manipulation'],
 'palindrome-permutation-ii': ['Hash Table', 'String', 'Backtracking'],
 'missing-number': ['Array',
  'Hash Table',
  'Math',
  'Binary Search',
  'Bit Manipulation',
  'Sorting'],
 'alien-dictionary': ['Array',
  'String',
  'Depth-First Search',
  'Breadth-First Search',
  'Graph',
  'Topological Sort'],
 'closest-binary-search-tree-value': ['Binary Search',
  'Tree',
  'Depth-First Search',
  'Binary Search Tree',
  'Binary Tree'],
 'encode-and-decode-strings': ['Array', 'String', 'Design'],
 'closest-binary-search-tree-value-ii': ['Two Pointers',
  'Stack',
  'Tree',
  'Depth-First Search',
  'Binary Search Tree',
  'Heap (Priority Queue)',
  'Binary Tree'],
 'integer-to-english-words': ['Math', 'String', 'Recursion'],
 'h-index': ['Array', 'Sorting', 'Counting Sort'],
 'h-index-ii': ['Array', 'Binary Search'],
 'paint-fence': ['Dynamic Programming'],
 'find-the-celebrity': ['Two Pointers', 'Graph', 'Interactive'],
 'first-bad-version': ['Binary Search', 'Interactive'],
 'perfect-squares': ['Math', 'Dynamic Programming', 'Breadth-First Search'],
 'wiggle-sort': ['Array', 'Greedy', 'Sorting'],
 'zigzag-iterator': ['Array', 'Design', 'Queue', 'Iterator'],
 'expression-add-operators': ['Math', 'String', 'Backtracking'],
 'move-zeroes': ['Array', 'Two Pointers'],
 'peeking-iterator': ['Array', 'Design', 'Iterator'],
 'inorder-successor-in-bst': ['Tree',
  'Depth-First Search',
  'Binary Search Tree',
  'Binary Tree'],
 'walls-and-gates': ['Array', 'Breadth-First Search', 'Matrix'],
 'find-the-duplicate-number': ['Array',
  'Two Pointers',

In [ ]:
def baseline(weights,str_x,str_y):
  name_sim=cosine_similarity(name_embeds[str_x].reshape(1,-1),name_embeds[str_y].reshape(1,-1))[0][0]
  code_sim=cosine_similarity(code_embeds[str_x].reshape(1,-1),code_embeds[str_y].reshape(1,-1))[0][0]
  set_x, set_y = set(tags[str_x]), set(tags[str_y])
  tags_sim = len(set_x & set_y) / len(set_x | set_y) if (set_x or set_y) else 1.0
  return np.dot(weights,[name_sim,code_sim,tags_sim])

In [ ]:
param_grid={
    'w_name':np.arange(0.05,0.96,0.05),
    'w_code':np.arange(0.05,0.96,0.05),
    'w_tag':np.arange(0.05,0.41,0.05)
}

In [ ]:
grid=[p for p in ParameterGrid(param_grid) if abs(sum([p['w_name'],p['w_code'],p['w_tag']]) -1)<0.01]
best_ndcg=0
best_score=-np.inf
best_mse=np.inf
best_weight=None

In [ ]:
df=pd.read_csv('similar_questions.csv')
df.tail()

,question1,question2,score
5117,insert-into-a-sorted-circular-linked-list,frog-jump,0.0
5118,length-of-the-longest-alphabetical-continuous-...,maximum-profit-in-job-scheduling,0.0
5119,design-bounded-blocking-queue,separate-the-digits-in-an-array,0.0
5120,maximum-size-subarray-sum-equals-k,the-skyline-problem,0.0
5121,watering-plants,better-compression-of-string,0.0

In [ ]:
exclude =["last-person-to-fit-in-the-bus",'jump-game-viii'] # cleand after going through DB of questions i have
rows_to_remove_mask=(df['question1'].isin(exclude) | df['question2'].isin(exclude)) # 11
df_filtered= df[~rows_to_remove_mask]
len(df_filtered)

5111

In [ ]:
pairs=[(rows['question1'],rows['question2'],rows['score']) for _,rows in df_filtered.iterrows()]
pairs

[('two-sum', '3sum', 1.0),
 ('two-sum', '4sum', 1.0),
 ('two-sum', 'two-sum-ii-input-array-is-sorted', 1.0),
 ('two-sum', 'two-sum-iii-data-structure-design', 1.0),
 ('two-sum', 'subarray-sum-equals-k', 1.0),
 ('two-sum', 'two-sum-iv-input-is-a-bst', 1.0),
 ('two-sum', 'two-sum-less-than-k', 1.0),
 ('two-sum', 'max-number-of-k-sum-pairs', 1.0),
 ('two-sum', 'count-good-meals', 1.0),
 ('two-sum', 'count-number-of-pairs-with-absolute-difference-k', 1.0),
 ('two-sum',
  'number-of-pairs-of-strings-with-concatenation-equal-to-target',
  1.0),
 ('two-sum', 'find-all-k-distant-indices-in-an-array', 1.0),
 ('two-sum', 'first-letter-to-appear-twice', 1.0),
 ('two-sum', 'number-of-excellent-pairs', 1.0),
 ('two-sum', 'number-of-arithmetic-triplets', 1.0),
 ('two-sum', 'node-with-highest-edge-score', 1.0),
 ('two-sum', 'check-distances-between-same-letters', 1.0),
 ('two-sum', 'find-subarrays-with-equal-sum', 1.0),
 ('two-sum', 'largest-positive-integer-that-exists-with-its-negative', 1.0),
 ('two-sum', 'number-of-distinct-averages', 1.0),
 ('two-sum', 'count-pairs-whose-sum-is-less-than-target', 1.0),
 ('add-two-numbers', 'multiply-strings', 1.0),
 ('add-two-numbers', 'add-binary', 1.0),
 ('add-two-numbers', 'sum-of-two-integers', 1.0),
 ('add-two-numbers', 'add-strings', 1.0),
 ('add-two-numbers', 'add-two-numbers-ii', 1.0),
 ('add-two-numbers', 'add-to-array-form-of-integer', 1.0),
 ('add-two-numbers', 'add-two-polynomials-represented-as-linked-lists', 1.0),
 ('add-two-numbers', 'double-a-number-represented-as-a-linked-list', 1.0),
 ('longest-substring-without-repeating-characters',
  'longest-substring-with-at-most-two-distinct-characters',
  1.0),
 ('longest-substring-without-repeating-characters',
  'longest-substring-with-at-most-k-distinct-characters',
  1.0),
 ('longest-substring-without-repeating-characters',
  'subarrays-with-k-different-integers',
  1.0),
 ('longest-substring-without-repeating-characters',
  'maximum-erasure-value',
  1.0),
 ('longest-substring-without-repeating-characters',
  'number-of-equal-count-substrings',
  1.0),
 ('longest-substring-without-repeating-characters',
  'minimum-consecutive-cards-to-pick-up',
  1.0),
 ('longest-substring-without-repeating-characters',
  'longest-nice-subarray',
  1.0),
 ('longest-substring-without-repeating-characters',
  'optimal-partition-of-string',
  1.0),
 ('longest-substring-without-repeating-characters',
  'count-complete-subarrays-in-an-array',
  1.0),
 ('longest-substring-without-repeating-characters',
  'find-longest-special-substring-that-occurs-thrice-ii',
  1.0),
 ('longest-substring-without-repeating-characters',
  'find-longest-special-substring-that-occurs-thrice-i',
  1.0),
 ('median-of-two-sorted-arrays', 'median-of-a-row-wise-sorted-matrix', 1.0),
 ('longest-palindromic-substring', 'shortest-palindrome', 1.0),
 ('longest-palindromic-substring', 'palindrome-permutation', 1.0),
 ('longest-palindromic-substring', 'palindrome-pairs', 1.0),
 ('longest-palindromic-substring', 'longest-palindromic-subsequence', 1.0),
 ('longest-palindromic-substring', 'palindromic-substrings', 1.0),
 ('longest-palindromic-substring',
  'maximum-number-of-non-overlapping-palindrome-substrings',
  1.0),
 ('reverse-integer', 'string-to-integer-atoi', 1.0),
 ('reverse-integer', 'reverse-bits', 1.0),
 ('reverse-integer', 'a-number-after-a-double-reversal', 1.0),
 ('reverse-integer',
  'count-number-of-distinct-integers-after-reverse-operations',
  1.0),
 ('string-to-integer-atoi', 'valid-number', 1.0),
 ('string-to-integer-atoi',
  'check-if-numbers-are-ascending-in-a-sentence',
  1.0),
 ('palindrome-number', 'palindrome-linked-list', 1.0),
 ('palindrome-number', 'find-palindrome-with-fixed-length', 1.0),
 ('palindrome-number', 'strictly-palindromic-number', 1.0),
 ('palindrome-number', 'count-symmetric-integers', 1.0),
 ('palindrome-number', 'find-the-count-of-good-integers', 1.0),
 ('palindrome-number', 'find-the-largest-palindrome-divisible-by-k', 1.0),
 ('regular-expression-matching', 'wildcard-matching', 1.0),
 ('container-with-most-water', 'trapping-rain-water', 1.0),
 ('container-with-most-water', 'maximum-tastiness-of-candy-basket', 1.0),
 ('container-with-most-water', 'house-robber-iv', 1.0),
 ('integer-to-roman', 'roman-to-integer', 1.0),
 ('integer-to-roman', 'integer-to-english-words', 1.0),
 ('longest-common-prefix',
  'smallest-missing-integer-greater-than-sequential-prefix-sum',
  1.0),
 ('longest-common-prefix',
  'find-the-length-of-the-longest-common-prefix',
  1.0),
 ('longest-common-prefix', 'longest-common-suffix-queries', 1.0),
 ('longest-common-prefix',
  'longest-common-prefix-after-at-most-one-removal',
  1.0),
 ('3sum', '3sum-closest', 1.0),
 ('3sum', '4sum', 1.0),
 ('3sum', '3sum-smaller', 1.0),
 ('3sum', 'number-of-arithmetic-triplets', 1.0),
 ('3sum', 'minimum-sum-of-mountain-triplets-i', 1.0),
 ('3sum', 'minimum-sum-of-mountain-triplets-ii', 1.0),
 ('3sum-closest', '3sum-smaller', 1.0),
 ('letter-combinations-of-a-phone-number', 'generate-parentheses', 1.0),
 ('letter-combinations-of-a-phone-number', 'combination-sum', 1.0),
 ('letter-combinations-of-a-phone-number', 'binary-watch', 1.0),
 ('letter-combinations-of-a-phone-number', 'count-number-of-texts', 1.0),
 ('letter-combinations-of-a-phone-number',
  'minimum-number-of-pushes-to-type-word-i',
  1.0),
 ('letter-combinations-of-a-phone-number',
  'minimum-number-of-pushes-to-type-word-ii',
  1.0),
 ('4sum', '4sum-ii', 1.0),
 ('4sum', 'count-special-quadruplets', 1.0),
 ('remove-nth-node-from-end-of-list', 'swapping-nodes-in-a-linked-list', 1.0),
 ('remove-nth-node-from-end-of-list',
  'delete-n-nodes-after-m-nodes-of-a-linked-list',
  1.0),
 ('remove-nth-node-from-end-of-list',
  'delete-the-middle-node-of-a-linked-list',
  1.0),
 ('valid-parentheses', 'generate-parentheses', 1.0),
 ('valid-parentheses', 'longest-valid-parentheses', 1.0),
 ('valid-parentheses', 'remove-invalid-parentheses', 1.0),
 ('valid-parentheses', 'check-if-word-is-valid-after-substitutions', 1.0),
 ('valid-parentheses', 'check-if-a-parentheses-string-can-be-valid', 1.0),
 ('valid-parentheses', 'move-pieces-to-obtain-a-string', 1.0),
 ('merge-two-sorted-lists', 'merge-k-sorted-lists', 1.0),
 ('merge-two-sorted-lists', 'merge-sorted-array', 1.0),
 ('merge-two-sorted-lists', 'sort-list', 1.0),
 ('merge-two-sorted-lists', 'shortest-word-distance-ii', 1.0),
 ('merge-two-sorted-lists',
  'add-two-polynomials-represented-as-linked-lists',
  1.0),
 ('merge-two-sorted-lists',
  'longest-common-subsequence-between-sorted-arrays',
  1.0),
 ('merge-two-sorted-lists', 'merge-two-2d-arrays-by-summing-values', 1.0),
 ('generate-parentheses', 'check-if-a-parentheses-string-can-be-valid', 1.0),
 ('merge-k-sorted-lists', 'ugly-number-ii', 1.0),
 ('merge-k-sorted-lists', 'smallest-subarrays-with-maximum-bitwise-or', 1.0),
 ('swap-nodes-in-pairs', 'reverse-nodes-in-k-group', 1.0),
 ('swap-nodes-in-pairs', 'swapping-nodes-in-a-linked-list', 1.0),
 ('reverse-nodes-in-k-group', 'swapping-nodes-in-a-linked-list', 1.0),
 ('reverse-nodes-in-k-group', 'reverse-nodes-in-even-length-groups', 1.0),
 ('remove-duplicates-from-sorted-array', 'remove-element', 1.0),
 ('remove-duplicates-from-sorted-array',
  'remove-duplicates-from-sorted-array-ii',
  1.0),
 ('remove-duplicates-from-sorted-array', 'apply-operations-to-an-array', 1.0),
 ('remove-duplicates-from-sorted-array', 'sum-of-distances', 1.0),
 ('remove-element', 'remove-linked-list-elements', 1.0),
 ('remove-element', 'move-zeroes', 1.0),
 ('find-the-index-of-the-first-occurrence-in-a-string',
  'shortest-palindrome',
  1.0),
 ('find-the-index-of-the-first-occurrence-in-a-string',
  'repeated-substring-pattern',
  1.0),
 ('substring-with-concatenation-of-all-words',
  'minimum-window-substring',
  1.0),
 ('next-permutation', 'permutations', 1.0),
 ('next-permutation', 'permutations-ii', 1.0),
 ('next-permutation', 'permutation-sequence', 1.0),
 ('next-permutation', 'palindrome-permutation-ii', 1.0),
 ('next-permutation',
  'minimum-adjacent-swaps-to-reach-the-kth-smallest-number',
  1.0),
 ('search-in-rotated-sorted-array', 'search-in-rotated-sorted-array-ii', 1.0),
 ('search-in-rotated-sorted-array',
  'find-minimum-in-rotated-sorted-array',
  1.0),
 ('search-in-rotated-sorted-array',
  'pour-water-between-buckets-to-make-water-levels-equal',
  1.0),
 ('find-first-and-last-position-of-element-in-sorted-array',
  'first-bad-version',
  1.0),
 ('find-first-and-last-position-of-element-in-sorted-array',
  'plates-between-candles',
  1.0),
 ('find-first-and-last-position-of-element-in-sorted-array',
  'find-target-indices-after-sorting-array',
  1.0),
 ('search-insert-position', 'first-bad-version', 1.0),
 ('search-insert-position',
  'minimum-operations-to-exceed-threshold-value-i',
  1.0),
 ('valid-sudoku', 'sudoku-solver', 1.0),
 ('valid-sudoku', 'check-if-every-row-and-column-contains-all-numbers', 1.0),
 ('sudoku-solver', 'unique-paths-iii', 1.0),
 ('count-and-say', 'encode-and-decode-strings', 1.0),
 ('count-and-say', 'string-compression', 1.0),
 ('combination-sum', 'combination-sum-ii', 1.0),
 ('combination-sum', 'combinations', 1.0),
 ('combination-sum', 'combination-sum-iii', 1.0),
 ('combination-sum', 'factor-combinations', 1.0),
 ('combination-sum', 'combination-sum-iv', 1.0),
 ('combination-sum', 'the-number-of-ways-to-make-the-sum', 1.0),
 ('first-missing-positive', 'missing-number', 1.0),
 ('first-missing-positive', 'find-the-duplicate-number', 1.0),
 ('first-missing-positive', 'find-all-numbers-disappeared-in-an-array', 1.0),
 ('first-missing-positive', 'couples-holding-hands', 1.0),
 ('first-missing-positive', 'smallest-number-in-infinite-set', 1.0),
 ('first-missing-positive',
  'maximum-number-of-integers-to-choose-from-a-range-i',
  1.0),
 ('first-missing-positive',
  'smallest-missing-non-negative-integer-after-operations',
  1.0),
 ('first-missing-positive',
  'maximum-number-of-integers-to-choose-from-a-range-ii',
  1.0),
 ('first-missing-positive',
  'smallest-missing-integer-greater-than-sequential-prefix-sum',
  1.0),
 ('trapping-rain-water', 'product-of-array-except-self', 1.0),
 ('trapping-rain-water', 'trapping-rain-water-ii', 1.0),
 ('trapping-rain-water', 'pour-water', 1.0),
 ('trapping-rain-water', 'maximum-value-of-an-ordered-triplet-ii', 1.0),
 ('multiply-strings', 'plus-one', 1.0),
 ('multiply-strings', 'add-binary', 1.0),
 ('multiply-strings', 'add-strings', 1.0),
 ('multiply-strings', 'apply-discount-to-prices', 1.0),
 ('wildcard-matching', 'substring-matching-pattern', 1.0),
 ('jump-game-ii', 'jump-game', 1.0),
 ('jump-game-ii', 'jump-game-iii', 1.0),
 ('jump-game-ii', 'jump-game-vii', 1.0),
 ('jump-game-ii', 'minimum-number-of-visited-cells-in-a-grid', 1.0),
 ('jump-game-ii', 'maximum-number-of-jumps-to-reach-the-last-index', 1.0),
 ('jump-game-ii', 'visit-array-positions-to-maximize-score', 1.0),
 ('permutations', 'permutations-ii', 1.0),
 ('permutations', 'permutation-sequence', 1.0),
 ('permutations', 'combinations', 1.0),
 ('permutations-ii', 'palindrome-permutation-ii', 1.0),
 ('permutations-ii', 'number-of-squareful-arrays', 1.0),
 ('rotate-image', 'determine-whether-matrix-can-be-obtained-by-rotation', 1.0),
 ('group-anagrams', 'valid-anagram', 1.0),
 ('group-anagrams', 'group-shifted-strings', 1.0),
 ('group-anagrams', 'find-resultant-array-after-removing-anagrams', 1.0),
 ('group-anagrams', 'count-anagrams', 1.0),
 ('powx-n', 'sqrtx', 1.0),
 ('powx-n', 'super-pow', 1.0),
 ('powx-n', 'count-collisions-of-monkeys-on-a-polygon', 1.0),
 ('n-queens', 'n-queens-ii', 1.0),
 ('n-queens', 'grid-illumination', 1.0),
 ('maximum-subarray', 'best-time-to-buy-and-sell-stock', 1.0),
 ('maximum-subarray', 'maximum-product-subarray', 1.0),
 ('maximum-subarray', 'degree-of-an-array', 1.0),
 ('maximum-subarray', 'longest-turbulent-subarray', 1.0),
 ('maximum-subarray', 'maximum-score-of-spliced-array', 1.0),
 ('maximum-subarray', 'maximum-absolute-sum-of-any-subarray', 1.0),
 ('maximum-subarray', 'maximum-subarray-sum-after-one-operation', 1.0),
 ('maximum-subarray', 'substring-with-largest-variance', 1.0),
 ('maximum-subarray', 'count-subarrays-with-score-less-than-k', 1.0),
 ('maximum-subarray', 'maximum-value-of-a-string-in-an-array', 1.0),
 ('maximum-subarray', 'find-the-substring-with-maximum-cost', 1.0),
 ('maximum-subarray', 'k-items-with-the-maximum-sum', 1.0),
 ('maximum-subarray', 'maximum-good-subarray-sum', 1.0),
 ('maximum-subarray',
  'maximize-subarray-sum-after-removing-all-occurrences-of-one-element',
  1.0),
 ('spiral-matrix', 'spiral-matrix-ii', 1.0),
 ('spiral-matrix', 'spiral-matrix-iii', 1.0),
 ('spiral-matrix', 'spiral-matrix-iv', 1.0),
 ('jump-game', 'jump-game-iii', 1.0),
 ('jump-game', 'jump-game-vii', 1.0),
 ('jump-game', 'minimum-number-of-visited-cells-in-a-grid', 1.0),
 ('jump-game', 'largest-element-in-an-array-after-merge-operations', 1.0),
 ('merge-intervals', 'insert-interval', 1.0),
 ('merge-intervals', 'meeting-rooms', 1.0),
 ('merge-intervals', 'meeting-rooms-ii', 1.0),
 ('merge-intervals', 'teemo-attacking', 1.0),
 ('merge-intervals', 'add-bold-tag-in-string', 1.0),
 ('merge-intervals', 'range-module', 1.0),
 ('merge-intervals', 'employee-free-time', 1.0),
 ('merge-intervals', 'partition-labels', 1.0),
 ('merge-intervals', 'interval-list-intersections', 1.0),
 ('merge-intervals', 'amount-of-new-area-painted-each-day', 1.0),
 ('merge-intervals', 'longest-substring-of-one-repeating-character', 1.0),
 ('merge-intervals', 'count-integers-in-intervals', 1.0),
 ('merge-intervals', 'divide-intervals-into-minimum-number-of-groups', 1.0),
 ('merge-intervals', 'determine-if-two-events-have-conflict', 1.0),
 ('merge-intervals', 'count-ways-to-group-overlapping-ranges', 1.0),
 ('merge-intervals', 'points-that-intersect-with-cars', 1.0),
 ('merge-intervals', 'count-days-without-meetings', 1.0),
 ('merge-intervals', 'minimize-connected-groups-by-inserting-interval', 1.0),
 ('insert-interval', 'range-module', 1.0),
 ('insert-interval', 'count-integers-in-intervals', 1.0),
 ('spiral-matrix-ii', 'spiral-matrix-iii', 1.0),
 ('spiral-matrix-ii', 'spiral-matrix-iv', 1.0),
 ('rotate-list', 'rotate-array', 1.0),
 ('rotate-list', 'split-linked-list-in-parts', 1.0),
 ('unique-paths', 'unique-paths-ii', 1.0),
 ('unique-paths', 'minimum-path-sum', 1.0),
 ('unique-paths', 'dungeon-game', 1.0),
 ('unique-paths', 'minimum-path-cost-in-a-grid', 1.0),
 ('unique-paths', 'minimum-cost-homecoming-of-a-robot-in-a-grid', 1.0),
 ('unique-paths',
  'number-of-ways-to-reach-a-position-after-exactly-k-steps',
  1.0),
 ('unique-paths', 'paths-in-matrix-whose-sum-is-divisible-by-k', 1.0),
 ('unique-paths-ii', 'unique-paths-iii', 1.0),
 ('unique-paths-ii', 'minimum-path-cost-in-a-grid', 1.0),
 ('unique-paths-ii', 'paths-in-matrix-whose-sum-is-divisible-by-k', 1.0),
 ('minimum-path-sum', 'dungeon-game', 1.0),
 ('minimum-path-sum', 'cherry-pickup', 1.0),
 ('minimum-path-sum', 'minimum-path-cost-in-a-grid', 1.0),
 ('minimum-path-sum', 'maximum-number-of-points-with-cost', 1.0),
 ('minimum-path-sum', 'minimum-cost-homecoming-of-a-robot-in-a-grid', 1.0),
 ('minimum-path-sum', 'paths-in-matrix-whose-sum-is-divisible-by-k', 1.0),
 ('minimum-path-sum',
  'check-if-there-is-a-path-with-equal-number-of-0s-and-1s',
  1.0),
 ('minimum-path-sum', 'minimum-cost-of-a-path-with-special-roads', 1.0),
 ('plus-one', 'add-binary', 1.0),
 ('plus-one', 'plus-one-linked-list', 1.0),
 ('plus-one', 'add-to-array-form-of-integer', 1.0),
 ('plus-one', 'minimum-operations-to-reduce-an-integer-to-0', 1.0),
 ('add-binary', 'add-to-array-form-of-integer', 1.0),
 ('text-justification', 'rearrange-spaces-between-words', 1.0),
 ('text-justification', 'divide-a-string-into-groups-of-size-k', 1.0),
 ('text-justification', 'split-message-based-on-limit', 1.0),
 ('sqrtx', 'valid-perfect-square', 1.0),
 ('climbing-stairs', 'min-cost-climbing-stairs', 1.0),
 ('climbing-stairs', 'fibonacci-number', 1.0),
 ('climbing-stairs', 'n-th-tribonacci-number', 1.0),
 ('climbing-stairs', 'minimum-rounds-to-complete-all-tasks', 1.0),
 ('climbing-stairs', 'count-number-of-ways-to-place-houses', 1.0),
 ('climbing-stairs',
  'number-of-ways-to-reach-a-position-after-exactly-k-steps',
  1.0),
 ('climbing-stairs', 'count-ways-to-build-good-strings', 1.0),
 ('climbing-stairs', 'frog-jump-ii', 1.0),
 ('climbing-stairs', 'find-number-of-ways-to-reach-the-k-th-stair', 1.0),
 ('climbing-stairs', 'the-number-of-ways-to-make-the-sum', 1.0),
 ('edit-distance', 'one-edit-distance', 1.0),
 ('edit-distance', 'delete-operation-for-two-strings', 1.0),
 ('edit-distance', 'minimum-ascii-delete-sum-for-two-strings', 1.0),
 ('edit-distance', 'uncrossed-lines', 1.0),
 ('edit-distance', 'minimum-white-tiles-after-covering-with-carpets', 1.0),
 ('edit-distance', 'longest-palindrome-after-substring-concatenation-ii', 1.0),
 ('edit-distance', 'minimum-steps-to-convert-string-with-operations', 1.0),
 ('set-matrix-zeroes', 'game-of-life', 1.0),
 ('set-matrix-zeroes', 'number-of-laser-beams-in-a-bank', 1.0),
 ('set-matrix-zeroes',
  'minimum-operations-to-remove-adjacent-ones-in-matrix',
  1.0),
 ('set-matrix-zeroes', 'remove-all-ones-with-row-and-column-flips-ii', 1.0),
 ('search-a-2d-matrix', 'search-a-2d-matrix-ii', 1.0),
 ('search-a-2d-matrix', 'split-message-based-on-limit', 1.0),
 ('sort-colors', 'sort-list', 1.0),
 ('sort-colors', 'wiggle-sort', 1.0),
 ('sort-colors', 'wiggle-sort-ii', 1.0),
 ('minimum-window-substring', 'minimum-size-subarray-sum', 1.0),
 ('minimum-window-substring', 'sliding-window-maximum', 1.0),
 ('minimum-window-substring', 'permutation-in-string', 1.0),
 ('minimum-window-substring',
  'smallest-range-covering-elements-from-k-lists',
  1.0),
 ('minimum-window-substring', 'minimum-window-subsequence', 1.0),
 ('minimum-window-substring',
  'count-substrings-that-can-be-rearranged-to-contain-a-string-ii',
  1.0),
 ('minimum-window-substring',
  'count-substrings-that-can-be-rearranged-to-contain-a-string-i',
  1.0),
 ('subsets', 'subsets-ii', 1.0),
 ('subsets', 'generalized-abbreviation', 1.0),
 ('subsets', 'letter-case-permutation', 1.0),
 ('subsets', 'find-array-given-subset-sums', 1.0),
 ('subsets', 'count-number-of-maximum-bitwise-or-subsets', 1.0),
 ('word-search', 'word-search-ii', 1.0),
 ('remove-duplicates-from-sorted-list-ii',
  'remove-duplicates-from-sorted-list',
  1.0),
 ('remove-duplicates-from-sorted-list-ii',
  'remove-duplicates-from-an-unsorted-linked-list',
  1.0),
 ('remove-duplicates-from-sorted-list',
  'remove-duplicates-from-an-unsorted-linked-list',
  1.0),
 ('largest-rectangle-in-histogram', 'maximal-rectangle', 1.0),
 ('largest-rectangle-in-histogram', 'maximum-score-of-a-good-subarray', 1.0),
 ('maximal-rectangle', 'maximal-square', 1.0),
 ('maximal-rectangle',
  'find-sorted-submatrices-with-maximum-element-at-most-k',
  1.0),
 ('partition-list', 'partition-array-according-to-given-pivot', 1.0),
 ('merge-sorted-array', 'squares-of-a-sorted-array', 1.0),
 ('merge-sorted-array', 'interval-list-intersections', 1.0),
 ('merge-sorted-array', 'take-k-of-each-character-from-left-and-right', 1.0),
 ('gray-code', '1-bit-and-2-bit-characters', 1.0),
 ('subsets-ii', 'find-array-given-subset-sums', 1.0),
 ('decode-ways', 'decode-ways-ii', 1.0),
 ('decode-ways', 'number-of-ways-to-separate-numbers', 1.0),
 ('decode-ways', 'count-number-of-texts', 1.0),
 ('reverse-linked-list-ii', 'reverse-linked-list', 1.0),
 ('restore-ip-addresses', 'ip-to-cidr', 1.0),
 ('binary-tree-inorder-traversal', 'validate-binary-search-tree', 1.0),
 ('binary-tree-inorder-traversal', 'binary-tree-preorder-traversal', 1.0),
 ('binary-tree-inorder-traversal', 'binary-tree-postorder-traversal', 1.0),
 ('binary-tree-inorder-traversal', 'binary-search-tree-iterator', 1.0),
 ('binary-tree-inorder-traversal', 'kth-smallest-element-in-a-bst', 1.0),
 ('binary-tree-inorder-traversal', 'closest-binary-search-tree-value-ii', 1.0),
 ('binary-tree-inorder-traversal', 'inorder-successor-in-bst', 1.0),
 ('binary-tree-inorder-traversal',

In [ ]:
from sklearn.model_selection import train_test_split

# Split pairs (stratify to balance 1.0/0.0)
train_pairs, val_pairs = train_test_split(
    pairs,
    test_size=0.2,  # 20% (~1024 rows) for val
    stratify=[p[2] for p in pairs],  # Balance pos/neg
    random_state=42
)

# Verify balance
print("Train positives:", sum(p[2] for p in train_pairs) / len(train_pairs))
print("Val positives:", sum(p[2] for p in val_pairs) / len(val_pairs))

Train positives: 0.49902152641878667
Val positives: 0.49853372434017595

In [ ]:
collc=[]
for param in grid:
  weights=[param['w_name'],param['w_code'],param['w_tag']]
  preds=[]
  for str_x,str_y,_ in val_pairs:
    score=baseline(weights,str_x,str_y)
    preds.append(score)
  # true=[p['score'] for p in val_pairs]
  true=[p[2] for p in val_pairs]
  ndcg=ndcg_score(np.asarray([true]),np.asarray([preds]),k=10)
  mse = mean_squared_error(true, preds)
  score = ndcg - mse
  pos_preds = [preds[k] for k in range(len(true)) if true[k] == 1.0]
  neg_preds = [preds[k] for k in range(len(true)) if true[k] == 0.0]
  print(f"Weights {weights}: Avg pos score {np.mean(pos_preds) if pos_preds else 0:.4f}, Avg neg score {np.mean(neg_preds) if neg_preds else 0:.4f}, NDCG {ndcg:.4f}, MSE {mse:.4f}, Score {score:.4f}")
  if score > best_score:
      best_score = score
      best_ndcg = ndcg
      best_mse = mse
      best_weight = param
      collc = []
  elif score == best_score:
      collc.append(param)

print("\nBest Score (NDCG - MSE):", best_score)
print("Best NDCG:", best_ndcg)
print("Best MSE:", best_mse)
print("Best Weights:", best_weight)
print("Tied Weights:", collc)

In [ ]:
# Best collectiong of scores i got

# Weights [0.45, 0.15000000000000002, 0.4]: Avg pos score 0.5967, Avg neg score 0.2995, NDCG 1.0000, MSE 0.1385, Score 0.8615
# Weights [0.35000000000000003, 0.25, 0.4]: Avg pos score 0.5850, Avg neg score 0.2841, NDCG 1.0000, MSE 0.1388, Score 0.8612
# Weights [0.4, 0.25, 0.35000000000000003]: Avg pos score 0.5958, Avg neg score 0.3054, NDCG 1.0000, MSE 0.1393, Score 0.8607
# Weights [0.4, 0.2, 0.4]: Avg pos score 0.5908, Avg neg score 0.2918, NDCG 1.0000, MSE 0.1385, Score 0.8615
# Weights [0.45, 0.15000000000000002, 0.4]: Avg pos score 0.5967, Avg neg score 0.2995, NDCG 1.0000, MSE 0.1385, Score 0.8615


1. Best Score (NDCG - MSE): 0.8610283220131238
2. Best NDCG: 1.0Best MSE: 0.13897167798687615
3. Best Weights: {'w_code': 0.15000000000000002, 'w_name': 0.45, 'w_tag': 0.4}
4. Tied Weights: []

# Best combination after grid search

In [ ]:
best_weights = [0.2, 0.4, 0.4]  # [w_name, w_code, w_tag]

# Assume train_pairs = list of (str_x, str_y, temp_score); update to continuous
scored_train_pairs = []
for str_x, str_y, _ in train_pairs:
    name_sim = cosine_similarity(name_embeds[str_x].reshape(1,-1), name_embeds[str_y].reshape(1,-1))[0][0]
    code_sim = cosine_similarity(code_embeds[str_x].reshape(1,-1), code_embeds[str_y].reshape(1,-1))[0][0]
    set_x, set_y = set(tags[str_x]), set(tags[str_y])
    tags_sim = len(set_x & set_y) / len(set_x | set_y) if (set_x or set_y) else 1.0
    score = np.dot(best_weights, [name_sim, code_sim, tags_sim])
    scored_train_pairs.append((str_x, str_y, score))

# Optional: Print avg scores for sanity
pos_scores = [s[2] for s in scored_train_pairs if s[2] > 0.5]  # Approx positives
neg_scores = [s[2] for s in scored_train_pairs if s[2] <= 0.5]
print("Avg pos score:", np.mean(pos_scores) if pos_scores else 0)
print("Avg neg score:", np.mean(neg_scores) if neg_scores else 0)

Avg pos score: 0.6746705160860254
Avg neg score: 0.3008328406922815

In [ ]:
scored_val_pairs=[]
for str_x, str_y, _ in val_pairs:
    name_sim = cosine_similarity(name_embeds[str_x].reshape(1,-1), name_embeds[str_y].reshape(1,-1))[0][0]
    code_sim = cosine_similarity(code_embeds[str_x].reshape(1,-1), code_embeds[str_y].reshape(1,-1))[0][0]
    set_x, set_y = set(tags[str_x]), set(tags[str_y])
    tags_sim = len(set_x & set_y) / len(set_x | set_y) if (set_x or set_y) else 1.0
    score = np.dot(best_weights, [name_sim, code_sim, tags_sim])
    scored_val_pairs.append((str_x, str_y, score))

# Optional: Print avg scores for sanity
pos_scores = [s[2] for s in scored_val_pairs if s[2] > 0.5]  # Approx positives
neg_scores = [s[2] for s in scored_val_pairs if s[2] <= 0.5]
print("Avg pos score:", np.mean(pos_scores) if pos_scores else 0)
print("Avg neg score:", np.mean(neg_scores) if neg_scores else 0)

Avg pos score: 0.6591381800098232
Avg neg score: 0.30157238824423954

In [ ]:
from datasets import Dataset
import random

train_data = []
for str_x, str_y, score in scored_train_pairs:
    # Assume questions is dict with slug keys: questions[str_x] = {'name_text': ..., 'code_text': ..., 'tags': [...]}
    text1 = f"Name: {data[str_x]['title']} | Code: {data[str_x]['code']} | Tags: {','.join(sorted(data[str_x]['tags']))}"
    text2 = f"Name: {data[str_y]['title']} | Code: {data[str_y]['code']} | Tags: {','.join(sorted(data[str_y]['tags']))}"
    train_data.append((text1, text2, score))

In [ ]:
val_data=[]
for str_x,str_y,score in scored_val_pairs:
    text1 = f"Name: {data[str_x]['title']} | Code: {data[str_x]['code']} | Tags: {','.join(sorted(data[str_x]['tags']))}"
    text2 = f"Name: {data[str_y]['title']} | Code: {data[str_y]['code']} | Tags: {','.join(sorted(data[str_y]['tags']))}"
    val_data.append((text1, text2, score))

In [ ]:
train_data[0]

('Name: As Far from Land as Possible | Code: // Time:  O(m * n)\n// Space: O(m * n)\n\nclass Solution {\npublic:\n    int maxDistance(vector<vector<int>>& grid) {\n        static const vector<pair<int, int>> directions{{0, 1}, {1, 0}, {0, -1}, {-1, 0}};\n        queue<pair<int, int>> q;\n        for (int i = 0; i < grid.size(); ++i) {\n            for (int j = 0; j < grid[i].size(); ++j) {\n                if (grid[i][j]) {\n                    q.emplace(i, j);\n                }\n            }\n        }\n        if (q.size() == grid.size() * grid[0].size()) {\n            return -1;\n        }\n        int level = -1;\n        while (!q.empty()) {\n            queue<pair<int, int>> next_q;\n            while (!q.empty()) {\n                const auto [x, y] = q.front(); q.pop();\n                for (const auto& [dx, dy] : directions) {\n                    const auto& nx = x + dx;\n                    const auto& ny = y + dy;\n                    if (!(0 <= nx && nx < grid.size() && \n                          0 <= ny && ny < grid[0].size() && \n                          grid[nx][ny] == 0)) {\n                        continue;\n                    }\n                    next_q.emplace(nx, ny);\n                    grid[nx][ny] = 1;\n                }\n            }\n            q = move(next_q);\n            ++level;\n        }\n        return level;\n    }\n};\n | Tags: Array,Breadth-First Search,Dynamic Programming,Matrix',
 "Name: Maximum Manhattan Distance After K Changes | Code: // Time:  O(n)\n// Space: O(1)\n\n// greedy\nclass Solution {\npublic:\n    int maxDistance(string s, int k) {\n        int result = 0;\n        for (int i = 0, x = 0, y = 0; i < size(s); ++i) {\n            if (s[i] == 'E') {\n                ++x;\n            } else if (s[i] == 'W') {\n                --x;\n            } else if (s[i] == 'N') {\n                ++y;\n            } else if (s[i] == 'S') {\n                --y;\n            }\n            result = max(result, min(abs(x) + abs(y) + 2 * k, i + 1));\n        }\n        return result;\n    }\n};\n | Tags: Counting,Hash Table,Math,String",
 np.float64(0.3427242051079267))

# UniXcoder fine tuning

In [ ]:
!pip uninstall -y torch-xla
!pip install --upgrade torch torchvision --index-url https://download.pytorch.org/whl/cpu
!pip install --upgrade sentence-transformers

Found existing installation: torch_xla 2.8.0
Uninstalling torch_xla-2.8.0:
  Successfully uninstalled torch_xla-2.8.0
Looking in indexes: https://download.pytorch.org/whl/cpu
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.3.0)
Collecting torch
  Downloading https://download.pytorch.org/whl/cpu/torch-2.8.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (29 kB)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.18.0)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cpu/torchvision-0.23.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.14.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.2)
Downloading https://download.pytorch.org/whl/cpu/torch-2.8.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl (183.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 MB 79.7 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/cpu/torchvision-0.23.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 76.4 MB/s eta 0:00:00
Installing collected packages: torch, torchvision
  Attempting uninstall: torch
    Found existing installation: torch 2.3.0
    Uninstalling torch-2.3.0:
      Successfully uninstalled torch-2.3.0
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.18.0
    Uninstalling torchvision-0.18.0:
      Successfully uninstalled torchvision-0.18.0
Successfully installed torch-2.8.0+cpu torchvision-0.23.0+cpu

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.1.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.55.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.8.0+cpu)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.34.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.14.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.7)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.7.34)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.6.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.8.3)

In [ ]:
import torch
import torch.nn as nn
from datasets import Dataset
from sentence_transformers import SentenceTransformer, losses, InputExample
from sentence_transformers.evaluation import EmbeddingSimilarityEvaluator
from sentence_transformers.trainer import SentenceTransformerTrainer
from sentence_transformers.training_args import SentenceTransformerTrainingArguments
from sentence_transformers.models import Transformer, Pooling
from transformers import TrainerCallback, RobertaTokenizer, RobertaModel
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
import random

# Set random seeds for reproducibility
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed(42)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
class ProgressCallback(TrainerCallback):
    def on_epoch_begin(self, args, state, control, **kwargs):
        print(f"Epoch {state.epoch + 1} starting...")

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs:
            # Filter out None values and format nicely
            formatted_logs = {k: f"{v:.4f}" if isinstance(v, float) else v
                            for k, v in logs.items() if v is not None}
            print(f"Step {logs.get('step', 'N/A')}: {formatted_logs}")

    def on_evaluate(self, args, state, control, logs=None, **kwargs):
        if logs:
            print(f"Evaluation results: {logs}")

In [ ]:
def create_unixcoder_sentence_transformer(max_seq_length=512):
    """
    Create a sentence-transformer compatible UniXcoder model
    UniXcoder is based on RoBERTa architecture
    """
    print("Creating UniXcoder sentence-transformer model...")
    try:
        # Load the transformer
        word_embedding_model = Transformer(
            'microsoft/unixcoder-base',
            max_seq_length=max_seq_length,
            model_args={'trust_remote_code': True}  # might need this
        )

        # Add pooling layer
        pooling_model = Pooling(
            word_embedding_model.get_word_embedding_dimension(),
            pooling_mode_cls_token=True,    # Use [CLS] token
            pooling_mode_max_tokens=False,  # Don't use max pooling
            pooling_mode_mean_tokens=False  # Don't use mean pooling
        )

        # Create the sentence transformer
        model = SentenceTransformer(
            modules=[word_embedding_model, pooling_model]
        )

        print("UniXcoder successfully wrapped in sentence-transformers")
        return model

    except Exception as e:
        print(f"Error creating UniXcoder wrapper: {e}")
        raise e

In [ ]:
def create_training_examples(data_tuples):
    """Convert data tuples to InputExample objects for sentence-transformers"""
    examples = []
    for text1, text2, score in data_tuples:
        examples.append(InputExample(texts=[str(text1), str(text2)], label=float(score)))
    return examples

In [ ]:
def fine_tune_unixcoder(
    train_data,
    val_data=None,
    output_dir='finetuned_unixcoder_model',
    num_epochs=3,
    batch_size=8,
    learning_rate=2e-5,
    warmup_ratio=0.1,
    eval_steps=100,
    save_steps=100,
    max_seq_length=512,
    loss_function='cosent'  # 'cosent', 'cosine', 'contrastive'
):
    """
    Complete UniXcoder fine-tuning pipeline
    """

    # Check device
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f"Using device: {device}")
    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")
        print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    # Create UniXcoder model
    print("Loading UniXcoder model...")
    try:
        model = create_unixcoder_sentence_transformer(max_seq_length=max_seq_length)
        model = model.to(device)
        print(" UniXcoder model loaded successfully")
    except Exception as e:
        print(f" Failed to load UniXcoder: {e}")
        raise e

    train_examples = train_data
    val_examples = [
        InputExample(texts=[row["text1"], row["text2"]], label=row["score"])
        for row in val_data
    ]
    evaluator = EmbeddingSimilarityEvaluator.from_input_examples(
        val_examples,
        name='unixcoder_leetcode_eval',
        show_progress_bar=True
    )
    print(f"Validation examples: {len(val_examples)}")
    # Loss Function
    loss = losses.CoSENTLoss(model)

    total_steps = len(train_examples) * num_epochs // batch_size
    warmup_steps = int(warmup_ratio * total_steps)

    print(f"Training configuration:")
    print(f"  Total examples: {len(train_examples)}")
    print(f"  Batch size: {batch_size}")
    print(f"  Epochs: {num_epochs}")
    print(f"  Total steps: {total_steps}")
    print(f"  Warmup steps: {warmup_steps}")
    print(f"  Learning rate: {learning_rate}")

    # Training arguments optimized for UniXcoder
    args = SentenceTransformerTrainingArguments(
        output_dir=output_dir,
        num_train_epochs=num_epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        gradient_accumulation_steps=1,
        warmup_steps=warmup_steps,
        learning_rate=learning_rate,

        # Mixed precision and optimization
        fp16=torch.cuda.is_available() and torch.cuda.get_device_capability()[0] >= 7,
        bf16=False,  # Set to True for A100/newer GPUs
        gradient_checkpointing=True,  # Save memory

        # Device settings
        use_cpu=not torch.cuda.is_available(),
        dataloader_num_workers=0,  # Avoid multiprocessing issues

        # Evaluation and saving
        eval_strategy='steps' if evaluator else 'no',
        eval_steps=eval_steps if evaluator else None,
        save_strategy='steps',
        save_steps=save_steps,
        load_best_model_at_end=True if evaluator else False,
        metric_for_best_model='eval_unixcoder_leetcode_eval_spearman_cosine' if evaluator else None,
        greater_is_better=True if evaluator else None,
        save_total_limit=3,

        # Logging
        logging_strategy='steps',
        logging_steps=50,  # More frequent logging
        report_to=None,  # Disable wandb/tensorboard

        # Reproducibility
        seed=42,
        data_seed=42,

        # Performance
        remove_unused_columns=False,
        prediction_loss_only=False,
    )

    # Create trainer
    trainer = SentenceTransformerTrainer(
        model=model,
        args=args,
        train_dataset=train_examples,
        loss=loss,
        evaluator=evaluator,
    )

    # Add progress callback
    trainer.add_callback(ProgressCallback())

    # Start training
    print("\n🚀 Starting UniXcoder fine-tuning...")
    print("="*60)

    try:
        trainer.train(resume_from_checkpoint=True)
        print("="*60)
        print(" Training completed successfully!")

    except Exception as e:
        print(f" Training failed: {e}")
        raise e

    # Save the model
    print(f"\n Saving model to {output_dir}")
    model.save(output_dir)

    # Create a clean final model
    final_model_path = f"{output_dir}_final"
    model.save(final_model_path)
    print(f" Final model saved to {final_model_path}")

In [ ]:
def create_training_dataset(data_tuples):
    return Dataset.from_dict({
        "text1": [str(t[0]) for t in data_tuples],
        "text2": [str(t[1]) for t in data_tuples],
        "score": [float(t[2]) for t in data_tuples],
    })

In [ ]:
train_dataset= create_training_dataset(train_data)
val_dataset = create_training_dataset(val_data)

In [ ]:
model, trainer = fine_tune_unixcoder(
      train_data=train_dataset,
      val_data=val_dataset,
      output_dir='/content/drive/MyDrive/leetcode_unixcoder',  # save path
      num_epochs=2,                        # How many times to go through the data
      batch_size=8,
      learning_rate=2e-5,
      max_seq_length=256,                 # Maximum length of input text
      loss_function='cosent'
  )

Using device: cpu
Loading UniXcoder model...
Loading UniXcoder model...
Creating UniXcoder sentence-transformer model...
UniXcoder not available directly, creating custom wrapper...

config.json:   0%|          | 0.00/691 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/504M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/504M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

UniXcoder successfully wrapped in sentence-transformers
✓ UniXcoder model loaded successfully
Validation examples: 1023
Training configuration:
  Total examples: 4088
  Batch size: 8
  Epochs: 2
  Total steps: 1022
  Warmup steps: 102
  Learning rate: 2e-05

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

🚀 Starting UniXcoder fine-tuning...
============================================================

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: sidpurk04 (sidpurk04-national-institute-of-technology-meghalaya) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

Epoch 2.5655577299412915 starting...

Step N/A: {'loss': '2.6601', 'grad_norm': '32.9889', 'learning_rate': '0.0000', 'epoch': '1.6634'}
Step N/A: {'loss': '2.5066', 'grad_norm': '42.4028', 'learning_rate': '0.0000', 'epoch': '1.7613'}

Batches:   0%|          | 0/64 [00:00<?, ?it/s]

Batches:   0%|          | 0/64 [00:00<?, ?it/s]

Step N/A: {'eval_unixcoder_leetcode_eval_pearson_cosine': '0.8823', 'eval_unixcoder_leetcode_eval_spearman_cosine': '0.8875', 'eval_runtime': '1662.8814', 'eval_samples_per_second': '0.0000', 'eval_steps_per_second': '0.0000', 'epoch': '1.7613'}
Step N/A: {'loss': '2.3788', 'grad_norm': '31.0104', 'learning_rate': '0.0000', 'epoch': '1.8591'}
Step N/A: {'loss': '2.3400', 'grad_norm': '31.3387', 'learning_rate': '0.0000', 'epoch': '1.9569'}

Batches:   0%|          | 0/64 [00:00<?, ?it/s]

Batches:   0%|          | 0/64 [00:00<?, ?it/s]

Step N/A: {'eval_unixcoder_leetcode_eval_pearson_cosine': '0.8845', 'eval_unixcoder_leetcode_eval_spearman_cosine': '0.8840', 'eval_runtime': '1667.6961', 'eval_samples_per_second': '0.0000', 'eval_steps_per_second': '0.0000', 'epoch': '1.9569'}
Step N/A: {'train_runtime': '18447.6437', 'train_samples_per_second': '0.4430', 'train_steps_per_second': '0.0550', 'total_flos': '0.0000', 'train_loss': '0.5353', 'epoch': '2.0000'}
============================================================
✅ Training completed successfully!

💾 Saving model to /content/drive/MyDrive/leetcode_unixcoder
✅ Final model saved to /content/drive/MyDrive/leetcode_unixcoder_final

TypeError: cannot unpack non-iterable NoneType object